
package br.com.fiap.winery.stubclasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "WineWarninServiceImplementationService", targetNamespace = "http://winery.fiap.com.br/", wsdlLocation = "http://localhost:8085/WineWarningService?wsdl")
public class WineWarninServiceImplementationService
    extends Service
{

    private static final URL WINEWARNINSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private static final WebServiceException WINEWARNINSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private static final QName WINEWARNINSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://winery.fiap.com.br/", "WineWarninServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/WineWarningService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WINEWARNINSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        WINEWARNINSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public WineWarninServiceImplementationService() {
        super(__getWsdlLocation(), WINEWARNINSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public WineWarninServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WINEWARNINSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public WineWarninServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, WINEWARNINSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public WineWarninServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WINEWARNINSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public WineWarninServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WineWarninServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WineWarningService
     */
    @WebEndpoint(name = "WineWarninServiceImplementationPort")
    public WineWarningService getWineWarninServiceImplementationPort() {
        return super.getPort(new QName("http://winery.fiap.com.br/", "WineWarninServiceImplementationPort"), WineWarningService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WineWarningService
     */
    @WebEndpoint(name = "WineWarninServiceImplementationPort")
    public WineWarningService getWineWarninServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://winery.fiap.com.br/", "WineWarninServiceImplementationPort"), WineWarningService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WINEWARNINSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw WINEWARNINSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return WINEWARNINSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
